/**
 * Refinement types for the SlipBox semantic engine.
 *
 * Refinement suggestions are advisory only — SlipBox never modifies user notes
 * automatically. Suggestions are generated by a local LLM agent and stored for
 * review. The user decides whether and how to apply them.
 *
 * Stored as /index/refinements.json in PrivateBox.
 */

import type { NoteId } from "./note";

export const REFINEMENT_TYPES = [
  "retitle",
  "split",
  "merge-suggest",
  "update",
] as const;

export type RefinementType = typeof REFINEMENT_TYPES[number];

export interface RefinementSuggestion {
  /** Unique key: `${noteId}:${type}` */
  id: string;
  noteId: NoteId;
  type: RefinementType;
  /** The proposed change (e.g. new title, split outline, merge target, updated text). */
  suggestion: string;
  /** Why this change is suggested. */
  reason: string;
  /** Related note IDs — used for merge-suggest to identify the merge target(s). */
  relatedNoteIds: NoteId[];
  generatedAt: string;
}

export interface RefinementsIndex {
  /** Keyed by `${noteId}:${type}` — one suggestion per note per type. */
  suggestions: Record<string, RefinementSuggestion>;
  updatedAt: string;
}

export const emptyRefinementsIndex = (): RefinementsIndex => ({
  suggestions: {},
  updatedAt: new Date().toISOString(),
});
